import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Exemplos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <header className='hidden md:block bg-indigo-500 w-full h-[10%] py-2'>
          <nav className='flex items-center justify-center gap-5 '>
            <Link className='p-3 bg-slate-800 text-white font-bold rounded-3xl hover:rounded-xl link-a  ' href={"/"}>Home</Link>
            <Link className='p-3 bg-slate-800 text-white font-bold rounded-3xl hover:rounded-xl link-a  ' href={"/pages/buttons"}>Buttons</Link>
            <Link className='p-3 bg-slate-800 text-white font-bold rounded-3xl hover:rounded-xl link-a  ' href={"/pages/inputs"}>Inputs</Link>
            <Link className='p-3 bg-slate-800 text-white font-bold rounded-3xl hover:rounded-xl link-a  ' href={"/pages/sociallinks"}>Social Links</Link>
            <Link className='p-3 bg-slate-800 text-white font-bold rounded-3xl hover:rounded-xl link-a  ' href={"/pages/loading"}>Loading</Link>
            <Link className='p-3 bg-slate-800 text-white font-bold rounded-3xl hover:rounded-xl link-a  ' href={"/pages/card"}>Card</Link>
            <Link className='p-3 bg-slate-800 text-white font-bold rounded-3xl hover:rounded-xl link-a  ' href={"/pages/boxes"}>Caixas</Link>
            <Link className='p-3 bg-slate-800 text-white font-bold rounded-3xl hover:rounded-xl link-a  ' href={"/pages/search"}>Search</Link>
            <Link className='p-3 bg-slate-800 text-white font-bold rounded-3xl hover:rounded-xl link-a  ' href={"#"}>Toggle</Link>
            <Link className='p-3 bg-slate-800 text-white font-bold rounded-3xl hover:rounded-xl link-a  ' href={"/pages/alert"}>Alert</Link>
            <Link className='p-3 bg-slate-800 text-white font-bold rounded-3xl hover:rounded-xl link-a  ' href={"/pages/drag"}>Arrastar</Link>
          </nav>
        </header>

        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
